name: Android Build

on:
    workflow_dispatch:
    push:
      paths:
        - android/**

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant gradlew permissions
        run: chmod +x android/OwOAssistant/gradlew

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: ./android/OwOAssistant

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: android/OwOAssistant/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} android/OwOAssistant/app/build/outputs/apk/release/owo-assistant.apk

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: android/OwOAssistant/app/build/outputs/apk/release/owo-assistant.apk
          tag_name: "build-${{ github.run_number }}"
          name: "Build #${{ github.run_number }}"
          body: |
            *Automated android client build (commit: ${{ github.sha }})*
            **Client Installation**
            1. Download the APK
            2. Open the APK on your Android device and tap install

            **Server Installation**
            1. Follow the installation instructions in the [README](https://github.com/OpEnchanter/owo-assistant/blob/main/README.md)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}