name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v**"

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant gradlew permissions
        run: chmod +x android/OwOAssistant/gradlew

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: ./android/OwOAssistant

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: android/OwOAssistant/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} android/OwOAssistant/app/build/outputs/apk/release/owo-assistant.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: android/OwOAssistant/app/build/outputs/apk/release/owo-assistant.apk

  build-standalone-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun Setup
        uses: oven-sh/setup-bun@v2

      - name: Bun Install
        run: bun install

      - name: Build Linux Executable
        run: bun build ./index.ts --compile --outfile ./owo-linux-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: standalone-linux
          path: server/owo-linux-x64

  build-standalone-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun Setup
        uses: oven-sh/setup-bun@v2

      - name: Bun Install
        run: bun install

      - name: Build Windows Executable
        run: bun build ./index.ts --compile --outfile ./owo-win-x64.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: standalone-windows
          path: server/owo-win-x64.exe

  publish:
    needs:
      - build-android
      - build-standalone-linux
      - build-standalone-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
              android/owo-assistant.apk
              standalone-windows/owo-win-x64.exe
              standalone-linux/owo-linux-x64
          tag_name: "build-${{ github.ref_name }}"
          name: "Build ${{ github.ref_name }}"
          body: |
            *Automated executable build (commit: ${{ github.sha }})*
            **Client Installation**
            1. Download the APK
            2. Open the APK on your Android device and tap install

            **Server Installation**
            1. Follow the installation instructions in the [README](https://github.com/OpEnchanter/owo-assistant/blob/main/README.md)
            OR

            1. Download the executable for your operating system from this release
            2. Run the executable
            3. Go to `http://localhost:8080`
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
